### PR TITLE
Also save and check the IP for tokens

### LINKED ISSUE #133: Add IP-Address to a token
This prevents from tokens being copied to another computer or so

### PR DESCRIPTION
**Pull request by TheHamloer**
Please check properly as I could not test the functionality!
Closes #133

### CODE REVIEW

**Comment by riesinger** [comment]
Why do you save the IP?

**Comment by TheHamloer** [comment]
So a token cannot be "stolen" from one PC and then used on another network. It's more or less like when you have to enter your Two-Factor-Authentication on a new network 😉

**Comment by riesinger** [comment]
So basically, you'd have to relogin every 24h, as you'll get a new IP *at least* every 24h. Also, this won't work on mobile devices😅 I see where you are going with this, but I think it won't work...

**Comment by TheHamloer** [comment]
I can see the flaw in my thinking 😅 
But then how do google or so track when you login on a new device/location?

**Comment by riesinger** [comment]
Oh well... User agents, device locations, OSs, ........ There are so many ways to fingerprint you, it's unbelieveable

**Pull request closed without merging**
