### PR TITLE
[WIP] Intermediate sharing merge

### LINKED ISSUE #137: Add sharing of files and folders to other users
- [X] Create share entry
- [X] Create entry of shared file in vfs
- [x] Add path check for shared folders
- [x] Handle shared files while copying, moving, ... properly

### LINKED ISSUE #165: Check for accessing content of a shared folder

### PR DESCRIPTION
**Pull request by TheHamloer**
Closes #137 
Closes #165

Sharing isn't 100% complete and probably still contains some bugs but we can still merge the first changes.
But please check the changes before merging 😉

### CODE REVIEW

**Comment by riesinger** [comment]
@TheHamloer do you know, why this comment was created?

**Comment by TheHamloer** [comment]
@riesinger Nope no idea 😅

**Comment by riesinger** [comment]
Will review this soon:tm:

**Comment by riesinger** [comment]
Marked as WIP, because @TheHamloer suggested that he wants to try implementing an SQL database into this branch

**Comment by TheHamloer** [comment]
This pr will be reopened due to spamming of the todo bot...

**Pull request closed without merging**
